broker:
  mysqlConnection: ${db_url}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/load-balancer-attributes: "access_logs.s3.enabled=true,access_logs.s3.bucket=${access_log_s3_bucket},access_logs.s3.prefix=${access_log_s3_path_prefix},routing.http2.enabled=true"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: ${https_cert_arn}
    alb.ingress.kubernetes.io/subnets: ${subnets}
    alb.ingress.kubernetes.io/tags: Environment=dev
  hosts:
    - host: ${hostname}
      paths:
        - path: /
